<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>Pure.RelationalSchema.Self.Schema</PackageId>
    <RootNamespace>Pure.RelationalSchema.Self.Schema</RootNamespace>
    <AssemblyName>Pure.RelationalSchema.Self.Schema</AssemblyName>
    <Authors>Dmitry Kurochkin</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kudima03/Pure.RelationalSchema.Self.Schema</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pure.RelationalSchema" Version="1.4.0" />
  </ItemGroup>
</Project>
